-- Enhanced Cooldown Manager addon for World of Warcraft
-- Author: Argium
-- Licensed under the GNU General Public License v3.0

local TestHelpers = assert(
    loadfile("Tests/TestHelpers.lua") or loadfile("TestHelpers.lua"),
    "Unable to load Tests/TestHelpers.lua"
)()

describe("GeneralOptions getters/setters/defaults", function()
    local originalGlobals
    local profile, defaults, SB, ns, settings

    setup(function()
        originalGlobals = TestHelpers.CaptureGlobals(TestHelpers.OPTIONS_GLOBALS)
    end)

    teardown(function()
        TestHelpers.RestoreGlobals(originalGlobals)
    end)

    before_each(function()
        TestHelpers.SetupOptionsGlobals()
        profile, defaults = TestHelpers.MakeOptionsProfile()
        SB, ns = TestHelpers.SetupOptionsEnv(profile, defaults)

        settings = TestHelpers.CollectSettings(function()
            TestHelpers.LoadChunk("UI/GeneralOptions.lua", "GeneralOptions")(nil, ns)
            TestHelpers.RegisterSectionSpec(SB, ns.GeneralOptions)
        end)
    end)

    -- Visibility toggles
    describe("hideWhenMounted", function()
        it("getter returns profile value", function()
            assert.is_true(settings["ECM_global_hideWhenMounted"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_hideWhenMounted"]:SetValue(false)
            assert.is_false(profile.global.hideWhenMounted)
        end)
        it("default matches expected", function()
            assert.is_true(settings["ECM_global_hideWhenMounted"]._default)
        end)
    end)

    describe("hideOutOfCombatInRestAreas", function()
        it("getter returns profile value", function()
            assert.is_false(settings["ECM_global_hideOutOfCombatInRestAreas"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_hideOutOfCombatInRestAreas"]:SetValue(true)
            assert.is_true(profile.global.hideOutOfCombatInRestAreas)
        end)
        it("default matches expected", function()
            assert.is_false(settings["ECM_global_hideOutOfCombatInRestAreas"]._default)
        end)
    end)

    -- Out of combat fade
    describe("outOfCombatFade.enabled", function()
        it("getter returns profile value", function()
            assert.is_false(settings["ECM_global_outOfCombatFade_enabled"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_outOfCombatFade_enabled"]:SetValue(true)
            assert.is_true(profile.global.outOfCombatFade.enabled)
        end)
        it("default matches expected", function()
            assert.is_false(settings["ECM_global_outOfCombatFade_enabled"]._default)
        end)
    end)

    describe("outOfCombatFade.opacity", function()
        it("getter returns profile value", function()
            assert.are.equal(60, settings["ECM_global_outOfCombatFade_opacity"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_outOfCombatFade_opacity"]:SetValue(80)
            assert.are.equal(80, profile.global.outOfCombatFade.opacity)
        end)
        it("default matches expected", function()
            assert.are.equal(60, settings["ECM_global_outOfCombatFade_opacity"]._default)
        end)
    end)

    describe("outOfCombatFade.exceptInInstance", function()
        it("getter returns profile value", function()
            assert.is_true(settings["ECM_global_outOfCombatFade_exceptInInstance"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_outOfCombatFade_exceptInInstance"]:SetValue(false)
            assert.is_false(profile.global.outOfCombatFade.exceptInInstance)
        end)
    end)

    describe("outOfCombatFade.exceptIfTargetCanBeAttacked", function()
        it("getter returns profile value", function()
            assert.is_true(settings["ECM_global_outOfCombatFade_exceptIfTargetCanBeAttacked"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_outOfCombatFade_exceptIfTargetCanBeAttacked"]:SetValue(false)
            assert.is_false(profile.global.outOfCombatFade.exceptIfTargetCanBeAttacked)
        end)
    end)

    describe("outOfCombatFade.exceptIfTargetCanBeHelped", function()
        it("getter returns profile value", function()
            assert.is_false(settings["ECM_global_outOfCombatFade_exceptIfTargetCanBeHelped"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_outOfCombatFade_exceptIfTargetCanBeHelped"]:SetValue(true)
            assert.is_true(profile.global.outOfCombatFade.exceptIfTargetCanBeHelped)
        end)
    end)

    -- Appearance
    describe("texture", function()
        it("getter returns profile value", function()
            assert.are.equal("Solid", settings["ECM_global_texture"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_texture"]:SetValue("Blizzard")
            assert.are.equal("Blizzard", profile.global.texture)
        end)
    end)

    describe("font", function()
        it("getter returns profile value", function()
            assert.are.equal("Expressway", settings["ECM_global_font"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_font"]:SetValue("Arial")
            assert.are.equal("Arial", profile.global.font)
        end)
    end)

    describe("fontSize", function()
        it("getter returns profile value", function()
            assert.are.equal(11, settings["ECM_global_fontSize"]:GetValue())
        end)
        it("getter applies transform for nil", function()
            profile.global.fontSize = nil
            assert.are.equal(11, settings["ECM_global_fontSize"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_fontSize"]:SetValue(14)
            assert.are.equal(14, profile.global.fontSize)
        end)
    end)

    describe("fontOutline", function()
        it("getter returns profile value", function()
            assert.are.equal("OUTLINE", settings["ECM_global_fontOutline"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_fontOutline"]:SetValue("THICKOUTLINE")
            assert.are.equal("THICKOUTLINE", profile.global.fontOutline)
        end)
    end)

    describe("fontShadow", function()
        it("getter returns profile value", function()
            assert.is_false(settings["ECM_global_fontShadow"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_fontShadow"]:SetValue(true)
            assert.is_true(profile.global.fontShadow)
        end)
    end)

    -- Layout
    describe("barHeight", function()
        it("getter returns profile value", function()
            assert.are.equal(22, settings["ECM_global_barHeight"]:GetValue())
        end)
        it("setter writes to profile", function()
            settings["ECM_global_barHeight"]:SetValue(30)
            assert.are.equal(30, profile.global.barHeight)
        end)
        it("default matches expected", function()
            assert.are.equal(22, settings["ECM_global_barHeight"]._default)
        end)
    end)

    it("does not register attached-stack settings on the General page", function()
        assert.is_nil(settings["ECM_global_offsetY"])
        assert.is_nil(settings["ECM_global_moduleSpacing"])
        assert.is_nil(settings["ECM_global_moduleGrowDirection"])
    end)
end)
